version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: scraper_db
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: scraper_password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scraper"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - scraper-network

  # Redis for Firecrawl
  redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"
    networks:
      - scraper-network

  # Firecrawl API with built-in Playwright
  firecrawl:
    image: ghcr.io/mendableai/firecrawl:latest
    environment:
      HOST: "0.0.0.0"
      PORT: 3002
      REDIS_URL: redis://redis:6379
      REDIS_RATE_LIMIT_URL: redis://redis:6379
      USE_DB_AUTHENTICATION: false
      BULL_AUTH_KEY: your-secret-key
      NUM_WORKERS_PER_QUEUE: 2
    ports:
      - "3002:3002"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - scraper-network
    # Give it more resources for Playwright
    deploy:
      resources:
        limits:
          memory: 2G

  # Your Scraper Application
  scraper:
    build: ./scraper
    environment:
      DATABASE_URL: postgresql://scraper:scraper_password@db:5432/scraper_db
      FIRECRAWL_URL: http://firecrawl:3002
    volumes:
      - ./scraper:/app
      - ./data/logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      firecrawl:
        condition: service_started
    restart: unless-stopped
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge